/**
 * Workflow Trigger Handler
 *
 * Issue #71 - LAUNCH BLOCKER
 *
 * HTTP endpoint to trigger book import workflows. Creates a new workflow instance
 * and returns the job ID for WebSocket progress tracking.
 *
 * POST /v2/import/workflow
 * Body: { isbn: string, source?: 'google_books' | 'openlibrary' | 'isbndb', userId?: string }
 *
 * Response (202 Accepted):
 * {
 *   "data": {
 *     "jobId": "import-9780451524935-1732558800000",
 *     "workflowId": "wf-abc123",
 *     "isbn": "9780451524935",
 *     "status": "started",
 *     "wsUrl": "wss://api.oooefam.net/ws/progress?jobId=..."
 *   },
 *   "metadata": { "timestamp": "..." }
 * }
 */

import type { IWebSocketConnectionDO } from '../types/durable-objects.js'
import { createProblemResponse, ErrorCodes } from '../utils/http/response-builder.js'
import type { BookImportInput } from '../workflows/import-book.js'

// Workflow binding type (will be generated by wrangler types)
interface WorkflowInstance {
  id: string
}

interface WorkflowBinding {
  create(options: { params: BookImportInput }): Promise<WorkflowInstance>
  get(id: string): Promise<{
    status(): Promise<{ status: string; output?: unknown; error?: string }>
    pause(): Promise<void>
    resume(): Promise<void>
    terminate(): Promise<void>
  }>
}

// Extended Env with Workflow binding
interface WorkflowEnv {
  BOOK_IMPORT_WORKFLOW: WorkflowBinding
  WEBSOCKET_CONNECTION_DO: DurableObjectNamespace
  // Feature flag for rollout
  WORKFLOW_ROLLOUT_PERCENT?: string
}

/**
 * Trigger a new book import workflow
 */
export async function triggerBookImportWorkflow(
  request: Request,
  env: WorkflowEnv,
): Promise<Response> {
  try {
    // Parse request body
    const body = (await request.json()) as {
      isbn?: string
      source?: 'google_books' | 'openlibrary' | 'isbndb'
      userId?: string
    }

    const { isbn, source = 'google_books', userId } = body

    // Validate ISBN
    if (!isbn) {
      return createProblemResponse(ErrorCodes.MISSING_PARAMETER, {
        detail: 'ISBN is required',
        instance: c.req.url,
        requestId: c.get('ctx')?.requestId,
        details: { field: 'isbn' },
        corsRequest: request,
      })
    }

    // Clean and validate ISBN format
    const cleanedIsbn = isbn.replace(/[-\s]/g, '')
    if (!/^\d{10}$|^\d{13}$/.test(cleanedIsbn)) {
      return createProblemResponse(ErrorCodes.INVALID_ISBN, {
        detail: 'Invalid ISBN format. Must be 10 or 13 digits.',
        instance: c.req.url,
        requestId: c.get('ctx')?.requestId,
        details: { isbn, cleanedIsbn },
        corsRequest: request,
      })
    }

    // Validate source
    const validSources = ['google_books', 'openlibrary', 'isbndb']
    if (!validSources.includes(source)) {
      return createProblemResponse(ErrorCodes.INVALID_REQUEST, {
        detail: `Invalid source. Must be one of: ${validSources.join(', ')}`,
        instance: c.req.url,
        requestId: c.get('ctx')?.requestId,
        details: { source, validSources },
        corsRequest: request,
      })
    }

    // Generate unique job ID
    const jobId = `import-${cleanedIsbn}-${Date.now()}`

    console.log(`[WorkflowTrigger] Creating workflow for ISBN ${cleanedIsbn}, jobId ${jobId}`)

    // Set up WebSocket auth token BEFORE creating workflow
    // This ensures the client can connect to receive progress updates
    const wsToken = crypto.randomUUID()
    const doId = env.WEBSOCKET_CONNECTION_DO.idFromName(jobId)
    const wsDoStub = env.WEBSOCKET_CONNECTION_DO.get(doId) as unknown as IWebSocketConnectionDO
    await wsDoStub.setAuthToken(wsToken)

    // Create Workflow instance
    const instance = await env.BOOK_IMPORT_WORKFLOW.create({
      params: {
        isbn: cleanedIsbn,
        jobId,
        userId,
        source: source as BookImportInput['source'],
      },
    })

    console.log(`[WorkflowTrigger] Workflow created with ID ${instance.id}`)

    // Build WebSocket URL for client (derive from request for multi-environment support)
    const requestUrl = new URL(request.url)
    const wsProtocol = requestUrl.protocol === 'https:' ? 'wss:' : 'ws:'
    const wsUrl = `${wsProtocol}//${requestUrl.host}/ws/progress?jobId=${encodeURIComponent(jobId)}&token=${encodeURIComponent(wsToken)}`

    // Return response with job details (202 Accepted for async operation)
    return new Response(
      JSON.stringify({
        jobId,
        workflowId: instance.id,
        isbn: cleanedIsbn,
        source,
        status: 'started',
        wsUrl,
      }),
      {
        status: 202, // Accepted - processing asynchronously
        headers: { 'Content-Type': 'application/json' },
      },
    )
  } catch (error) {
    const err = error as Error
    console.error('[WorkflowTrigger] Failed to create workflow:', err)

    // Check for specific workflow errors
    if (err.message?.includes('Workflow binding')) {
      return createProblemResponse('SERVICE_UNAVAILABLE', {
        detail: 'Workflow service not available. Please try again later.',
        instance: c.req.url,
        requestId: c.get('ctx')?.requestId,
        details: { error: err.message },
        corsRequest: request,
      })
    }

    return createProblemResponse(ErrorCodes.INTERNAL_ERROR, {
      detail: 'Failed to start book import workflow',
      instance: c.req.url,
      requestId: c.get('ctx')?.requestId,
      details: { error: err.message },
      corsRequest: request,
    })
  }
}

/**
 * Get status of a running workflow
 */
export async function getWorkflowStatus(
  request: Request,
  env: WorkflowEnv,
  workflowId: string,
): Promise<Response> {
  try {
    if (!workflowId) {
      return createProblemResponse(ErrorCodes.MISSING_PARAMETER, {
        detail: 'Workflow ID is required',
        instance: c.req.url,
        requestId: c.get('ctx')?.requestId,
        details: { field: 'workflowId' },
        corsRequest: request,
      })
    }

    // Get workflow instance
    const instance = await env.BOOK_IMPORT_WORKFLOW.get(workflowId)
    const status = await instance.status()

    return new Response(
      JSON.stringify({
        workflowId,
        status: status.status,
        output: status.output,
        error: status.error,
      }),
      {
        status: 200,
        headers: { 'Content-Type': 'application/json' },
      },
    )
  } catch (error) {
    const err = error as Error
    console.error('[WorkflowStatus] Failed to get status:', err)

    if (err.message?.includes('not found')) {
      return createProblemResponse(ErrorCodes.NOT_FOUND, {
        detail: 'Workflow not found',
        instance: c.req.url,
        requestId: c.get('ctx')?.requestId,
        details: { workflowId },
        corsRequest: request,
      })
    }

    return createProblemResponse(ErrorCodes.INTERNAL_ERROR, {
      detail: 'Failed to get workflow status',
      instance: c.req.url,
      requestId: c.get('ctx')?.requestId,
      details: { error: err.message },
      corsRequest: request,
    })
  }
}
