/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns API health status
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search/isbn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search by ISBN
         * @description Search for a book by ISBN-10 or ISBN-13
         */
        get: operations["searchByISBN"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search/title": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search by title
         * @description Search for books by title
         */
        get: operations["searchByTitle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Canonical API response format */
        ResponseEnvelope: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["Book"];
            metadata: {
                /**
                 * @description Data source provider
                 * @enum {string}
                 */
                source: "google_books" | "open_library" | "isbndb";
                /** @description Whether result was served from cache */
                cached: boolean;
                /**
                 * Format: date-time
                 * @description Response timestamp
                 */
                timestamp: string;
            };
        };
        /** @description Canonical book metadata object */
        Book: {
            /** @description ISBN-13 (primary identifier) */
            isbn: string;
            /** @description Book title */
            title: string;
            /** @description Primary author name */
            author?: string;
            /** @description Publisher name */
            publisher?: string;
            /** @description Publication date (YYYY-MM-DD or YYYY) */
            publishedDate?: string;
            /** @description Number of pages */
            pageCount?: number;
            /**
             * Format: uri
             * @description Cover image URL
             */
            coverUrl?: string;
            /** @description Book description/synopsis */
            description?: string;
        };
        /** @description Error response format */
        ErrorResponse: {
            /** @enum {boolean} */
            success: false;
            error: {
                /**
                 * @description Machine-readable error code
                 * @enum {string}
                 */
                code: "MISSING_ISBN" | "INVALID_ISBN" | "NOT_FOUND" | "RATE_LIMIT_EXCEEDED" | "CIRCUIT_OPEN" | "API_ERROR" | "INTERNAL_ERROR";
                /** @description Human-readable error message */
                message: string;
                /** @description HTTP status code */
                statusCode: number;
                /** @description Whether the request can be retried */
                retryable?: boolean;
                /** @description Milliseconds to wait before retry (if retryable) */
                retryAfterMs?: number;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
        };
    };
    searchByISBN: {
        parameters: {
            query: {
                /** @description ISBN-10 or ISBN-13 (digits only, no hyphens) */
                isbn: string;
                /** @description Include all editions of the book */
                includeEditions?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Book found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"];
                };
            };
            /** @description Invalid ISBN format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Book not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    searchByTitle: {
        parameters: {
            query: {
                /** @description Book title search query */
                q: string;
                /** @description Maximum number of results */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"];
                };
            };
        };
    };
}
