/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v3/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get API capabilities
         * @description Returns API feature availability, limits, and deprecation notices. Clients should call this on app startup.
         */
        get: operations["getCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/recommendations/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get weekly book recommendations
         * @description Returns global weekly book recommendations. Non-personalized curated picks generated every Sunday at midnight UTC.
         */
        get: operations["getWeeklyRecommendations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/books/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search books
         * @description Unified search supporting multiple modes: text, semantic, similar
         */
        get: operations["searchBooks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/books/{isbn}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get book by ISBN */
        get: operations["getBookByISBN"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/books/enrich": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enrich books with metadata */
        post: operations["enrichBooks"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SearchResponse: {
            success: boolean;
            data: {
                books?: components["schemas"]["Book"][];
                total?: number;
            };
            metadata: components["schemas"]["ResponseMetadata"];
        };
        BookResponse: {
            success: boolean;
            data: components["schemas"]["Book"];
            metadata: components["schemas"]["ResponseMetadata"];
        };
        EnrichRequest: {
            isbns: string[];
            /** @default false */
            includeEmbedding: boolean;
        };
        EnrichResponse: {
            success: boolean;
            data: {
                books?: components["schemas"]["Book"][];
                found?: number;
                requested?: number;
            };
            metadata: components["schemas"]["ResponseMetadata"];
        };
        Book: {
            /** @description 13-digit ISBN (example: 9780439708180) */
            isbn: string;
            /** @description 10-digit ISBN if available (example: 0439708184) */
            isbn10?: string;
            /** @description Book title */
            title: string;
            /** @description Book subtitle */
            subtitle?: string;
            /** @description List of author names */
            authors: string[];
            /** @description Publisher name */
            publisher?: string;
            /** @description Publication date (ISO 8601 or partial format) */
            publishedDate?: string;
            /** @description Book description/synopsis */
            description?: string;
            /** @description Number of pages */
            pageCount?: number;
            /** @description Book categories/genres */
            categories?: string[];
            /** @description ISO 639-1 language code (e.g., "en") */
            language?: string;
            /**
             * Format: uri
             * @description Cover image URL
             */
            coverUrl?: string;
            /**
             * Format: uri
             * @description Thumbnail image URL
             */
            thumbnailUrl?: string;
            /** @description OpenLibrary work key (e.g., OL82563W) */
            workKey?: string;
            /** @description OpenLibrary edition key (e.g., OL7353617M) */
            editionKey?: string;
            /**
             * @description Data source provider
             * @enum {string}
             */
            provider: "alexandria" | "google_books" | "open_library" | "isbndb";
            /** @description Data quality score 0-100 */
            quality: number;
        };
        ErrorResponse: {
            /** @enum {boolean} */
            success: false;
            error: {
                code: string;
                message: string;
                retryable?: boolean;
            };
        };
        ResponseMetadata: {
            /** Format: date-time */
            timestamp: string;
            requestId?: string;
            cached?: boolean;
            /** @description Request processing time in milliseconds */
            processingTime?: number;
        };
        /** @description API capabilities (iOS-compatible flat format) */
        CapabilitiesResponse: {
            features: components["schemas"]["CapabilitiesFeatures"];
            limits: components["schemas"]["CapabilitiesLimits"];
            /** @description API version */
            version: string;
        };
        CapabilitiesFeatures: {
            /** @description Semantic search enabled */
            semantic_search: boolean;
            /** @description Similar books search enabled */
            similar_books: boolean;
            /** @description Weekly recommendations enabled */
            weekly_recommendations: boolean;
            /** @description SSE streaming enabled */
            sse_streaming: boolean;
            /** @description Batch enrichment enabled */
            batch_enrichment: boolean;
            /** @description CSV import enabled */
            csv_import: boolean;
        };
        CapabilitiesLimits: {
            /** @description Semantic search requests per minute */
            semantic_search_rpm: number;
            /** @description Text search requests per minute */
            text_search_rpm: number;
            /** @description Maximum rows in CSV import */
            csv_max_rows: number;
            /** @description Maximum photos in batch scan */
            batch_max_photos: number;
        };
        RecommendationsResponse: {
            success: boolean;
            data: {
                /** @description Week start date (ISO 8601) */
                weekOf: string;
                recommendations: components["schemas"]["Recommendation"][];
                /** @description Number of recommendations returned */
                count: number;
                /** @description Total recommendations available */
                totalAvailable: number;
            };
            metadata: components["schemas"]["ResponseMetadata"];
        };
        Recommendation: {
            /** @description Book ISBN */
            isbn: string;
            /** @description Book title */
            title: string;
            /** @description Primary author */
            author: string;
            /**
             * Format: uri
             * @description Cover image URL
             */
            coverUrl?: string;
            /** @description Why this book is recommended */
            reason: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API capabilities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getWeeklyRecommendations: {
        parameters: {
            query?: {
                /** @description Number of recommendations (1-20) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Weekly recommendations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationsResponse"];
                };
            };
            /** @description No recommendations available */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    searchBooks: {
        parameters: {
            query: {
                /** @description Search query */
                q: string;
                mode?: "text" | "semantic" | "similar";
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getBookByISBN: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                isbn: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Book details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookResponse"];
                };
            };
            /** @description Book not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    enrichBooks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrichRequest"];
            };
        };
        responses: {
            /** @description Enriched books */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichResponse"];
                };
            };
        };
    };
}
